services:
  db:
    image: postgres:15-alpine
    container_name: smarket_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7575"
      POSTGRES_DB: "smarket_shop"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: